import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/logging/app_logger.dart';
import 'clipboard_history_entry.dart';
import 'clipboard_history_provider.dart';

final _log = AppLogger('ClipboardHistoryMonitorService');

/// Listens for clipboard entries the native per-platform clipboard monitor
/// (issues 04-06) reports and feeds them into [clipboardHistoryProvider].
///
/// Shares the `com.whispaste.clipboard_history` channel with
/// [MethodChannelSelfWriteSignal] (`self_write_signal.dart`), which only
/// ever *invokes* `markSelfWrite` on it -- this service only *receives*
/// `clipEntryDetected` calls, so the two coexist on the same channel name
/// without conflict.
///
/// The privacy-exclusion filter (`shouldExcludeForPrivacy`) is applied
/// here, in the Dart core, per PRD.md -- native monitors report every entry
/// plus its `org.nspasteboard.*` / Windows privacy flags, they never decide
/// on their own to drop one.
class ClipboardHistoryMonitorService extends Notifier<void> {
  static const _channelName = 'com.whispaste.clipboard_history';

  @override
  void build() {
    final channel = const MethodChannel(_channelName)
      ..setMethodCallHandler(_handleNativeCall);
    ref.onDispose(() => channel.setMethodCallHandler(null));
  }

  Future<void> _handleNativeCall(MethodCall call) async {
    if (call.method != 'clipEntryDetected') return;
    final args = call.arguments;
    if (args is! Map) return;

    final flags = ClipboardPrivacyFlags(
      transient: args['transient'] as bool? ?? false,
      concealed: args['concealed'] as bool? ?? false,
      autoGenerated: args['autoGenerated'] as bool? ?? false,
    );
    if (shouldExcludeForPrivacy(flags)) {
      _log.debug('clipEntryDetected: skipped (privacy-excluded)');
      return;
    }

    final capturedAtMs = args['capturedAtMs'] as int?;
    final capturedAt = capturedAtMs != null
        ? DateTime.fromMillisecondsSinceEpoch(capturedAtMs)
        : DateTime.now();

    final entry = switch (args['kind'] as String?) {
      'image' => _imageEntry(args, capturedAt),
      'text' => _textEntry(args, capturedAt),
      _ => null,
    };
    if (entry == null) {
      _log.warning('clipEntryDetected: malformed payload, ignoring');
      return;
    }

    ref.read(clipboardHistoryProvider.notifier).add(entry);
  }

  ClipboardHistoryEntry? _textEntry(Map args, DateTime capturedAt) {
    final text = args['text'] as String?;
    if (text == null || text.isEmpty) return null;
    return ClipboardHistoryEntry.text(text, capturedAt: capturedAt);
  }

  ClipboardHistoryEntry? _imageEntry(Map args, DateTime capturedAt) {
    final bytes = args['imageBytes'] as Uint8List?;
    if (bytes == null || bytes.isEmpty) return null;
    return ClipboardHistoryEntry.image(bytes, capturedAt: capturedAt);
  }
}

final clipboardHistoryMonitorServiceProvider =
    NotifierProvider<ClipboardHistoryMonitorService, void>(
      ClipboardHistoryMonitorService.new,
    );
