import 'dart:convert';

enum ClipboardEntryKind { text, image }

/// Privacy-exclusion flags surfaced by the native clipboard monitor.
///
/// Mirrors macOS `org.nspasteboard.{Transient,Concealed,AutoGenerated}Type`
/// and the Windows `CanIncludeInClipboardHistory` /
/// `ExcludeClipboardContentFromMonitorProcessing` conventions -- both
/// platforms use this to keep password managers out of clipboard history.
class ClipboardPrivacyFlags {
  const ClipboardPrivacyFlags({
    this.transient = false,
    this.concealed = false,
    this.autoGenerated = false,
  });

  final bool transient;
  final bool concealed;
  final bool autoGenerated;
}

bool shouldExcludeForPrivacy(ClipboardPrivacyFlags flags) =>
    flags.transient || flags.concealed || flags.autoGenerated;

/// A single RAM-only clipboard history entry. Never persisted to disk.
class ClipboardHistoryEntry {
  ClipboardHistoryEntry.text(String text, {required this.capturedAt})
    : kind = ClipboardEntryKind.text,
      textValue = text,
      imageBytes = null,
      byteSize = utf8.encode(text).length;

  ClipboardHistoryEntry.image(List<int> bytes, {required this.capturedAt})
    : kind = ClipboardEntryKind.image,
      textValue = null,
      imageBytes = List.unmodifiable(bytes),
      byteSize = bytes.length;

  final ClipboardEntryKind kind;
  final String? textValue;
  final List<int>? imageBytes;
  final int byteSize;
  final DateTime capturedAt;

  /// Never includes [textValue]/[imageBytes] -- clipboard content must
  /// never end up in logs or breadcrumbs.
  @override
  String toString() =>
      'ClipboardHistoryEntry(kind: $kind, byteSize: $byteSize, '
      'capturedAt: $capturedAt)';
}
