# Gitleaks configuration for WhisPaste
# https://github.com/gitleaks/gitleaks

title = "WhisPaste gitleaks config"

[allowlist]
  description = "Allowlist for false positives"

  regexTarget = "match"
  commits = ["3e202004ec33e483964ff040548f75961594b046"]

  [[allowlist.rules]]
    description = "Test API key in Dart test files"
    regex = '''sk-test-\d+'''
    path = '''.*_test\.dart'''
