import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:whispaste/services/clipboard_history/clipboard_history_monitor_service.dart';
import 'package:whispaste/services/clipboard_history/clipboard_history_provider.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const channelName = 'com.whispaste.clipboard_history';
  const codec = StandardMethodCodec();
  final binaryMessenger =
      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger;

  Future<void> sendFromNative(String method, Object? args) {
    return binaryMessenger.handlePlatformMessage(
      channelName,
      codec.encodeMethodCall(MethodCall(method, args)),
      (_) {},
    );
  }

  late ProviderContainer container;

  setUp(() {
    container = ProviderContainer();
    // Establish the method call handler by reading the service once, the
    // same way WpServiceBootstrap keeps it alive for the app lifetime.
    container.listen(clipboardHistoryMonitorServiceProvider, (_, _) {});
  });

  tearDown(() => container.dispose());

  test('clipEntryDetected with text adds a text entry', () async {
    await sendFromNative('clipEntryDetected', {
      'kind': 'text',
      'text': 'copied from Finder',
      'capturedAtMs': 1700000000000,
      'transient': false,
      'concealed': false,
      'autoGenerated': false,
    });

    final entries = container.read(clipboardHistoryProvider);
    expect(entries, hasLength(1));
    expect(entries.single.textValue, 'copied from Finder');
  });

  test('clipEntryDetected with image bytes adds an image entry', () async {
    await sendFromNative('clipEntryDetected', {
      'kind': 'image',
      'imageBytes': Uint8List.fromList([1, 2, 3, 4]),
      'capturedAtMs': 1700000000000,
      'transient': false,
      'concealed': false,
      'autoGenerated': false,
    });

    final entries = container.read(clipboardHistoryProvider);
    expect(entries, hasLength(1));
    expect(entries.single.imageBytes, [1, 2, 3, 4]);
  });

  test('a transient entry (password manager copy) is not added', () async {
    await sendFromNative('clipEntryDetected', {
      'kind': 'text',
      'text': 'super-secret-password',
      'capturedAtMs': 1700000000000,
      'transient': true,
      'concealed': false,
      'autoGenerated': false,
    });

    expect(container.read(clipboardHistoryProvider), isEmpty);
  });

  test('a concealed entry is not added', () async {
    await sendFromNative('clipEntryDetected', {
      'kind': 'text',
      'text': 'concealed content',
      'capturedAtMs': 1700000000000,
      'transient': false,
      'concealed': true,
      'autoGenerated': false,
    });

    expect(container.read(clipboardHistoryProvider), isEmpty);
  });

  test('an unknown method is ignored', () async {
    await sendFromNative('somethingElse', null);

    expect(container.read(clipboardHistoryProvider), isEmpty);
  });

  test('a malformed payload (missing text) is ignored', () async {
    await sendFromNative('clipEntryDetected', {
      'kind': 'text',
      'capturedAtMs': 1700000000000,
      'transient': false,
      'concealed': false,
      'autoGenerated': false,
    });

    expect(container.read(clipboardHistoryProvider), isEmpty);
  });
}
