/// Unit tests for [ClipboardHistoryEntry] and the privacy-exclusion filter.
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:whispaste/services/clipboard_history/clipboard_history_entry.dart';

void main() {
  group('ClipboardHistoryEntry', () {
    test('text entry reports its UTF-8 byte size', () {
      final entry = ClipboardHistoryEntry.text(
        'hello',
        capturedAt: DateTime(2026, 1, 1),
      );
      expect(entry.kind, ClipboardEntryKind.text);
      expect(entry.byteSize, 5);
    });

    test('image entry reports the raw byte length', () {
      final bytes = List<int>.filled(1024, 0);
      final entry = ClipboardHistoryEntry.image(
        bytes,
        capturedAt: DateTime(2026, 1, 1),
      );
      expect(entry.kind, ClipboardEntryKind.image);
      expect(entry.byteSize, 1024);
    });
  });

  group('shouldExcludeForPrivacy', () {
    test('excludes when any privacy flag is set', () {
      expect(
        shouldExcludeForPrivacy(const ClipboardPrivacyFlags(transient: true)),
        isTrue,
      );
      expect(
        shouldExcludeForPrivacy(const ClipboardPrivacyFlags(concealed: true)),
        isTrue,
      );
      expect(
        shouldExcludeForPrivacy(
          const ClipboardPrivacyFlags(autoGenerated: true),
        ),
        isTrue,
      );
    });

    test('does not exclude when no privacy flag is set', () {
      expect(shouldExcludeForPrivacy(const ClipboardPrivacyFlags()), isFalse);
    });
  });
}
