#!/usr/bin/env bash
# guard_mas_plugin_registrant.sh — Xcode build phase, runs before Compile
# Sources, on every configuration (not just MAS).
#
# `macos/Flutter/GeneratedPluginRegistrant.swift` is regenerated by
# `flutter build`/`flutter pub get` on every run (it's a "Generated file. Do
# not edit." header, and Flutter means it — confirmed by watching a hand-
# added guard get silently wiped mid-session). It unconditionally calls
# `AutoUpdaterMacosPlugin.register(...)`. That plugin wraps Sparkle, whose
# framework strip_mas_incompatible_frameworks.sh deletes from the MAS
# bundle entirely (see that script's comment for the full chain). Calling
# .register() on a type from a framework that's no longer in the bundle
# crashes with an unresolved symbol at the call site, so this guard is load-
# bearing, not cosmetic — it must survive every single MAS build, not just
# the one where it was hand-added.
#
# Runs regardless of CONFIGURATION (previously gated on "MAS" only): the
# guard is a no-op for every other config, since MAS_BUILD is never defined
# there, but a plain `flutter run -d macos` Debug build never triggers an
# Xcode rebuild between hot restarts, so the MAS-only gate left the working
# tree looking permanently dirty for the whole session between the app's
# (re)launches and the pre-commit hook's own self-heal (which only fires on
# files actually staged). Un-gating it means every ordinary app (re)launch
# heals the file too, not just a MAS build or a commit.
#
# Idempotent: safe to run on a freshly-regenerated file (adds the guard) or
# an already-patched one (no-op). The actual patch lives in
# patch_plugin_registrant_guard.py, shared with .githooks/pre-commit, which
# self-heals the working-tree file before it can be committed unguarded —
# this build phase remains the last line of defense for a build made from a
# tree where that hook didn't run (e.g. --no-verify).
set -euo pipefail

REGISTRANT="${SRCROOT}/Flutter/GeneratedPluginRegistrant.swift"

python3 "${SRCROOT}/patch_plugin_registrant_guard.py" "$REGISTRANT"
