#!/usr/bin/env bash
# guard_mas_plugin_registrant.sh — Xcode build phase (MAS configuration
# only), runs before Compile Sources.
#
# `macos/Flutter/GeneratedPluginRegistrant.swift` is regenerated by
# `flutter build`/`flutter pub get` on every run (it's a "Generated file. Do
# not edit." header, and Flutter means it — confirmed by watching a hand-
# added guard get silently wiped mid-session). It unconditionally calls
# `AutoUpdaterMacosPlugin.register(...)`. That plugin wraps Sparkle, whose
# framework strip_mas_incompatible_frameworks.sh deletes from the MAS
# bundle entirely (see that script's comment for the full chain). Calling
# .register() on a type from a framework that's no longer in the bundle
# crashes with an unresolved symbol at the call site, so this guard is load-
# bearing, not cosmetic — it must survive every single MAS build, not just
# the one where it was hand-added.
#
# Idempotent: safe to run on a freshly-regenerated file (adds the guard) or
# an already-patched one (no-op).
set -euo pipefail

if [[ "${CONFIGURATION:-}" != "MAS" ]]; then
  exit 0
fi

REGISTRANT="${SRCROOT}/Flutter/GeneratedPluginRegistrant.swift"

if [[ ! -f "$REGISTRANT" ]]; then
  echo "warning: $REGISTRANT not found — nothing to guard."
  exit 0
fi

if grep -q '#if !MAS_BUILD' "$REGISTRANT"; then
  echo "GeneratedPluginRegistrant.swift already guards AutoUpdaterMacosPlugin — nothing to do."
  exit 0
fi

python3 - "$REGISTRANT" <<'PYEOF'
import re
import sys

path = sys.argv[1]
with open(path) as f:
    content = f.read()

pattern = r'(  AutoUpdaterMacosPlugin\.register\(with: registry\.registrar\(forPlugin: "AutoUpdaterMacosPlugin"\)\)\n)'
replacement = '  #if !MAS_BUILD\n\\1  #endif\n'
new_content, n = re.subn(pattern, replacement, content)

if n == 0:
    print("warning: AutoUpdaterMacosPlugin.register(...) line not found — Flutter's generated code may have changed shape.", file=sys.stderr)
    sys.exit(0)

with open(path, "w") as f:
    f.write(new_content)
print(f"guard_mas_plugin_registrant: guarded {n} occurrence(s) in {path}")
PYEOF
