#!/usr/bin/env bash
# guard_mas_plugin_registrant.sh — Xcode build phase (MAS configuration
# only), runs before Compile Sources.
#
# `macos/Flutter/GeneratedPluginRegistrant.swift` is regenerated by
# `flutter build`/`flutter pub get` on every run (it's a "Generated file. Do
# not edit." header, and Flutter means it — confirmed by watching a hand-
# added guard get silently wiped mid-session). It unconditionally calls
# `AutoUpdaterMacosPlugin.register(...)`. That plugin wraps Sparkle, whose
# framework strip_mas_incompatible_frameworks.sh deletes from the MAS
# bundle entirely (see that script's comment for the full chain). Calling
# .register() on a type from a framework that's no longer in the bundle
# crashes with an unresolved symbol at the call site, so this guard is load-
# bearing, not cosmetic — it must survive every single MAS build, not just
# the one where it was hand-added.
#
# Idempotent: safe to run on a freshly-regenerated file (adds the guard) or
# an already-patched one (no-op). The actual patch lives in
# patch_plugin_registrant_guard.py, shared with .githooks/pre-commit, which
# self-heals the working-tree file before it can be committed unguarded —
# this build phase remains the last line of defense for a build made from a
# tree where that hook didn't run (e.g. --no-verify).
set -euo pipefail

if [[ "${CONFIGURATION:-}" != "MAS" ]]; then
  exit 0
fi

REGISTRANT="${SRCROOT}/Flutter/GeneratedPluginRegistrant.swift"

python3 "${SRCROOT}/patch_plugin_registrant_guard.py" "$REGISTRANT"
