// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// dart:ffi bindings for whisper.cpp v1.8.4 (libwhisper).
/// Generated with package:ffigen against include/whisper.h. Proof-of-concept.
///
class WhisperBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  WhisperBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  WhisperBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Char> whisper_version() {
    return _whisper_version();
  }

  late final _whisper_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'whisper_version',
      );
  late final _whisper_version = _whisper_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Various functions for loading a ggml whisper model. Allocate (almost) all
  /// memory needed for the model. Return NULL on failure
  ffi.Pointer<whisper_context> whisper_init_from_file_with_params(
    ffi.Pointer<ffi.Char> path_model,
    whisper_context_params params,
  ) {
    return _whisper_init_from_file_with_params(path_model, params);
  }

  late final _whisper_init_from_file_with_paramsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<whisper_context> Function(
            ffi.Pointer<ffi.Char>,
            whisper_context_params,
          )
        >
      >('whisper_init_from_file_with_params');
  late final _whisper_init_from_file_with_params =
      _whisper_init_from_file_with_paramsPtr
          .asFunction<
            ffi.Pointer<whisper_context> Function(
              ffi.Pointer<ffi.Char>,
              whisper_context_params,
            )
          >();

  /// Frees all allocated memory
  void whisper_free(ffi.Pointer<whisper_context> ctx) {
    return _whisper_free(ctx);
  }

  late final _whisper_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<whisper_context>)>
      >('whisper_free');
  late final _whisper_free = _whisper_freePtr
      .asFunction<void Function(ffi.Pointer<whisper_context>)>();

  /// Print system information
  ffi.Pointer<ffi.Char> whisper_print_system_info() {
    return _whisper_print_system_info();
  }

  late final _whisper_print_system_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'whisper_print_system_info',
      );
  late final _whisper_print_system_info = _whisper_print_system_infoPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  whisper_context_params whisper_context_default_params() {
    return _whisper_context_default_params();
  }

  late final _whisper_context_default_paramsPtr =
      _lookup<ffi.NativeFunction<whisper_context_params Function()>>(
        'whisper_context_default_params',
      );
  late final _whisper_context_default_params =
      _whisper_context_default_paramsPtr
          .asFunction<whisper_context_params Function()>();

  whisper_full_params whisper_full_default_params(
    WhisperSamplingStrategy strategy,
  ) {
    return _whisper_full_default_params(strategy.value);
  }

  late final _whisper_full_default_paramsPtr =
      _lookup<
        ffi.NativeFunction<whisper_full_params Function(ffi.UnsignedInt)>
      >('whisper_full_default_params');
  late final _whisper_full_default_params = _whisper_full_default_paramsPtr
      .asFunction<whisper_full_params Function(int)>();

  /// Run the entire model: PCM -> log mel spectrogram -> encoder -> decoder ->
  /// text Not thread safe for same context Uses the specified decoding strategy
  /// to obtain the text.
  int whisper_full(
    ffi.Pointer<whisper_context> ctx,
    whisper_full_params params,
    ffi.Pointer<ffi.Float> samples,
    int n_samples,
  ) {
    return _whisper_full(ctx, params, samples, n_samples);
  }

  late final _whisper_fullPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<whisper_context>,
            whisper_full_params,
            ffi.Pointer<ffi.Float>,
            ffi.Int,
          )
        >
      >('whisper_full');
  late final _whisper_full = _whisper_fullPtr
      .asFunction<
        int Function(
          ffi.Pointer<whisper_context>,
          whisper_full_params,
          ffi.Pointer<ffi.Float>,
          int,
        )
      >();

  /// Number of generated text segments A segment can be a few words, a
  /// sentence, or even a paragraph.
  int whisper_full_n_segments(ffi.Pointer<whisper_context> ctx) {
    return _whisper_full_n_segments(ctx);
  }

  late final _whisper_full_n_segmentsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<whisper_context>)>
      >('whisper_full_n_segments');
  late final _whisper_full_n_segments = _whisper_full_n_segmentsPtr
      .asFunction<int Function(ffi.Pointer<whisper_context>)>();

  /// Get the text of the specified segment
  ffi.Pointer<ffi.Char> whisper_full_get_segment_text(
    ffi.Pointer<whisper_context> ctx,
    int i_segment,
  ) {
    return _whisper_full_get_segment_text(ctx, i_segment);
  }

  late final _whisper_full_get_segment_textPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<whisper_context>, ffi.Int)
        >
      >('whisper_full_get_segment_text');
  late final _whisper_full_get_segment_text = _whisper_full_get_segment_textPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<whisper_context>, int)
      >();

  /// Hand-added (not from the original ffigen pass): redirects whisper.cpp/
  /// ggml's internal log output away from the stderr default. See
  /// `ggml_log_set`'s doc comment in ggml.h: "If this is not called, or NULL
  /// is supplied, everything is output on stderr." — fatal in a Windows GUI
  /// process with no attached console (FLUTTER_WHISPASTE-BB).
  void whisper_log_set(
    ffi.Pointer<ffi.NativeFunction<GgmlLogCallbackNative>> log_callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    _whisper_log_set(log_callback, user_data);
  }

  late final _whisper_log_setPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.NativeFunction<GgmlLogCallbackNative>>,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('whisper_log_set');
  late final _whisper_log_set = _whisper_log_setPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.NativeFunction<GgmlLogCallbackNative>>,
          ffi.Pointer<ffi.Void>,
        )
      >();
}

/// `typedef void (*ggml_log_callback)(enum ggml_log_level level, const char
/// * text, void * user_data);` — native signature for [WhisperBindings.
/// whisper_log_set]'s callback parameter.
typedef GgmlLogCallbackNative =
    ffi.Void Function(
      ffi.Int32 level,
      ffi.Pointer<ffi.Char> text,
      ffi.Pointer<ffi.Void> user_data,
    );

/// C interface
final class whisper_context extends ffi.Opaque {}

final class whisper_state extends ffi.Opaque {}

/// Available sampling strategies
enum WhisperSamplingStrategy {
  /// similar to OpenAI's GreedyDecoder
  WHISPER_SAMPLING_GREEDY(0),

  /// similar to OpenAI's BeamSearchDecoder
  WHISPER_SAMPLING_BEAM_SEARCH(1);

  final int value;
  const WhisperSamplingStrategy(this.value);

  static WhisperSamplingStrategy fromValue(int value) => switch (value) {
    0 => WHISPER_SAMPLING_GREEDY,
    1 => WHISPER_SAMPLING_BEAM_SEARCH,
    _ => throw ArgumentError(
      'Unknown value for WhisperSamplingStrategy: $value',
    ),
  };
}

typedef whisper_token = ffi.Int32;
typedef Dartwhisper_token = int;

final class UnnamedStruct1 extends ffi.Struct {
  /// ref:
  /// https://github.com/openai/whisper/blob/f82bc59f5ea234d4b97fb2860842ed38519f7e65/whisper/transcribe.py#L264
  @ffi.Int()
  external int best_of;
}

final class UnnamedStruct2 extends ffi.Struct {
  /// ref:
  /// https://github.com/openai/whisper/blob/f82bc59f5ea234d4b97fb2860842ed38519f7e65/whisper/transcribe.py#L265
  @ffi.Int()
  external int beam_size;

  /// TODO: not implemented, ref: https://arxiv.org/pdf/2204.05424.pdf
  @ffi.Float()
  external double patience;
}

final class whisper_token_data extends ffi.Opaque {}

final class whisper_grammar_element extends ffi.Opaque {}

final class whisper_vad_params extends ffi.Struct {
  /// Probability threshold to consider as speech.
  @ffi.Float()
  external double threshold;

  /// Min duration for a valid speech segment.
  @ffi.Int()
  external int min_speech_duration_ms;

  /// Min silence duration to consider speech as ended.
  @ffi.Int()
  external int min_silence_duration_ms;

  /// Max duration of a speech segment before forcing a new segment.
  @ffi.Float()
  external double max_speech_duration_s;

  /// Padding added before and after speech segments.
  @ffi.Int()
  external int speech_pad_ms;

  /// Overlap in seconds when copying audio samples from speech segment.
  @ffi.Float()
  external double samples_overlap;
}

/// Parameters for the whisper_full() function If you change the order or add
/// new parameters, make sure to update the default values in whisper.cpp:
/// whisper_full_default_params()
final class whisper_full_params extends ffi.Struct {
  @ffi.UnsignedInt()
  external int strategyAsInt;

  WhisperSamplingStrategy get strategy =>
      WhisperSamplingStrategy.fromValue(strategyAsInt);

  @ffi.Int()
  external int n_threads;

  /// max tokens to use from past text as prompt for the decoder
  @ffi.Int()
  external int n_max_text_ctx;

  /// start offset in ms
  @ffi.Int()
  external int offset_ms;

  /// audio duration to process in ms
  @ffi.Int()
  external int duration_ms;

  @ffi.Bool()
  external bool translate;

  /// do not use past transcription (if any) as initial prompt for the decoder
  @ffi.Bool()
  external bool no_context;

  /// do not generate timestamps
  @ffi.Bool()
  external bool no_timestamps;

  /// force single segment output (useful for streaming)
  @ffi.Bool()
  external bool single_segment;

  /// print special tokens (e.g. <SOT>, <EOT>, <BEG>, etc.)
  @ffi.Bool()
  external bool print_special;

  /// print progress information
  @ffi.Bool()
  external bool print_progress;

  /// print results from within whisper.cpp (avoid it, use callback instead)
  @ffi.Bool()
  external bool print_realtime;

  /// print timestamps for each text segment when printing realtime
  @ffi.Bool()
  external bool print_timestamps;

  /// enable token-level timestamps
  @ffi.Bool()
  external bool token_timestamps;

  /// timestamp token probability threshold (~0.01)
  @ffi.Float()
  external double thold_pt;

  /// timestamp token sum probability threshold (~0.01)
  @ffi.Float()
  external double thold_ptsum;

  /// max segment length in characters
  @ffi.Int()
  external int max_len;

  /// split on word rather than on token (when used with max_len)
  @ffi.Bool()
  external bool split_on_word;

  /// max tokens per segment (0 = no limit)
  @ffi.Int()
  external int max_tokens;

  /// enable debug_mode provides extra info (eg. Dump log_mel)
  @ffi.Bool()
  external bool debug_mode;

  /// overwrite the audio context size (0 = use default)
  @ffi.Int()
  external int audio_ctx;

  /// enable tinydiarize speaker turn detection
  @ffi.Bool()
  external bool tdrz_enable;

  /// A regular expression that matches tokens to suppress
  external ffi.Pointer<ffi.Char> suppress_regex;

  /// tokens to provide to the whisper decoder as initial prompt these are
  /// prepended to any existing text context from a previous call use
  /// whisper_tokenize() to convert text to tokens maximum of
  /// whisper_n_text_ctx()/2 tokens are used (typically 224)
  external ffi.Pointer<ffi.Char> initial_prompt;

  /// if true, always prepend initial_prompt to every decode window (may reduce
  /// conditioning on previous text)
  @ffi.Bool()
  external bool carry_initial_prompt;

  external ffi.Pointer<whisper_token> prompt_tokens;

  @ffi.Int()
  external int prompt_n_tokens;

  /// for auto-detection, set to nullptr, "" or "auto"
  external ffi.Pointer<ffi.Char> language;

  @ffi.Bool()
  external bool detect_language;

  /// ref:
  /// https://github.com/openai/whisper/blob/f82bc59f5ea234d4b97fb2860842ed38519f7e65/whisper/decoding.py#L89
  @ffi.Bool()
  external bool suppress_blank;

  /// non-speech tokens, ref:
  /// https://github.com/openai/whisper/blob/7858aa9c08d98f75575035ecd6481f462d66ca27/whisper/tokenizer.py#L224-L253
  @ffi.Bool()
  external bool suppress_nst;

  /// initial decoding temperature, ref: https://ai.stackexchange.com/a/32478
  @ffi.Float()
  external double temperature;

  /// ref:
  /// https://github.com/openai/whisper/blob/f82bc59f5ea234d4b97fb2860842ed38519f7e65/whisper/decoding.py#L97
  @ffi.Float()
  external double max_initial_ts;

  /// ref:
  /// https://github.com/openai/whisper/blob/f82bc59f5ea234d4b97fb2860842ed38519f7e65/whisper/transcribe.py#L267
  @ffi.Float()
  external double length_penalty;

  /// fallback parameters ref:
  /// https://github.com/openai/whisper/blob/f82bc59f5ea234d4b97fb2860842ed38519f7e65/whisper/transcribe.py#L274-L278
  @ffi.Float()
  external double temperature_inc;

  /// similar to OpenAI's "compression_ratio_threshold"
  @ffi.Float()
  external double entropy_thold;

  @ffi.Float()
  external double logprob_thold;

  @ffi.Float()
  external double no_speech_thold;

  external UnnamedStruct1 greedy;

  external UnnamedStruct2 beam_search;

  /// called for every newly generated text segment
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<whisper_context> ctx,
        ffi.Pointer<whisper_state> state,
        ffi.Int n_new,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  new_segment_callback;

  external ffi.Pointer<ffi.Void> new_segment_callback_user_data;

  /// called on each progress update
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<whisper_context> ctx,
        ffi.Pointer<whisper_state> state,
        ffi.Int progress,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  progress_callback;

  external ffi.Pointer<ffi.Void> progress_callback_user_data;

  /// called each time before the encoder starts
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Bool Function(
        ffi.Pointer<whisper_context> ctx,
        ffi.Pointer<whisper_state> state,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  encoder_begin_callback;

  external ffi.Pointer<ffi.Void> encoder_begin_callback_user_data;

  /// called each time before ggml computation starts
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Void> data)>
  >
  abort_callback;

  external ffi.Pointer<ffi.Void> abort_callback_user_data;

  /// called by each decoder to filter obtained logits
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<whisper_context> ctx,
        ffi.Pointer<whisper_state> state,
        ffi.Pointer<whisper_token_data> tokens,
        ffi.Int n_tokens,
        ffi.Pointer<ffi.Float> logits,
        ffi.Pointer<ffi.Void> user_data,
      )
    >
  >
  logits_filter_callback;

  external ffi.Pointer<ffi.Void> logits_filter_callback_user_data;

  external ffi.Pointer<ffi.Pointer<whisper_grammar_element>> grammar_rules;

  @ffi.Size()
  external int n_grammar_rules;

  @ffi.Size()
  external int i_start_rule;

  @ffi.Float()
  external double grammar_penalty;

  /// Enable VAD
  @ffi.Bool()
  external bool vad;

  /// Path to VAD model
  external ffi.Pointer<ffi.Char> vad_model_path;

  external whisper_vad_params vad_params;
}

enum whisper_alignment_heads_preset {
  WHISPER_AHEADS_NONE(0),

  /// All heads from the N-top-most text-layers
  WHISPER_AHEADS_N_TOP_MOST(1),
  WHISPER_AHEADS_CUSTOM(2),
  WHISPER_AHEADS_TINY_EN(3),
  WHISPER_AHEADS_TINY(4),
  WHISPER_AHEADS_BASE_EN(5),
  WHISPER_AHEADS_BASE(6),
  WHISPER_AHEADS_SMALL_EN(7),
  WHISPER_AHEADS_SMALL(8),
  WHISPER_AHEADS_MEDIUM_EN(9),
  WHISPER_AHEADS_MEDIUM(10),
  WHISPER_AHEADS_LARGE_V1(11),
  WHISPER_AHEADS_LARGE_V2(12),
  WHISPER_AHEADS_LARGE_V3(13),
  WHISPER_AHEADS_LARGE_V3_TURBO(14);

  final int value;
  const whisper_alignment_heads_preset(this.value);

  static whisper_alignment_heads_preset fromValue(int value) => switch (value) {
    0 => WHISPER_AHEADS_NONE,
    1 => WHISPER_AHEADS_N_TOP_MOST,
    2 => WHISPER_AHEADS_CUSTOM,
    3 => WHISPER_AHEADS_TINY_EN,
    4 => WHISPER_AHEADS_TINY,
    5 => WHISPER_AHEADS_BASE_EN,
    6 => WHISPER_AHEADS_BASE,
    7 => WHISPER_AHEADS_SMALL_EN,
    8 => WHISPER_AHEADS_SMALL,
    9 => WHISPER_AHEADS_MEDIUM_EN,
    10 => WHISPER_AHEADS_MEDIUM,
    11 => WHISPER_AHEADS_LARGE_V1,
    12 => WHISPER_AHEADS_LARGE_V2,
    13 => WHISPER_AHEADS_LARGE_V3,
    14 => WHISPER_AHEADS_LARGE_V3_TURBO,
    _ => throw ArgumentError(
      'Unknown value for whisper_alignment_heads_preset: $value',
    ),
  };
}

final class whisper_ahead extends ffi.Opaque {}

final class whisper_aheads extends ffi.Struct {
  @ffi.Size()
  external int n_heads;

  external ffi.Pointer<whisper_ahead> heads;
}

final class whisper_context_params extends ffi.Struct {
  @ffi.Bool()
  external bool use_gpu;

  @ffi.Bool()
  external bool flash_attn;

  /// CUDA device
  @ffi.Int()
  external int gpu_device;

  /// [EXPERIMENTAL] Token-level timestamps with DTW
  @ffi.Bool()
  external bool dtw_token_timestamps;

  @ffi.UnsignedInt()
  external int dtw_aheads_presetAsInt;

  whisper_alignment_heads_preset get dtw_aheads_preset =>
      whisper_alignment_heads_preset.fromValue(dtw_aheads_presetAsInt);

  @ffi.Int()
  external int dtw_n_top;

  external whisper_aheads dtw_aheads;

  /// TODO: remove
  @ffi.Size()
  external int dtw_mem_size;
}

const int WHISPER_SAMPLE_RATE = 16000;

const int WHISPER_N_FFT = 400;

const int WHISPER_HOP_LENGTH = 160;

const int WHISPER_CHUNK_SIZE = 30;
