<#
.SYNOPSIS
    Generates user-friendly, bilingual release notes from a raw git-cliff changelog.

.DESCRIPTION
    Takes a structured changelog (from git-cliff) and uses the OpenAI API to produce
    audience-friendly release notes in English and German. Sensitive information
    (API keys, internal paths, webhook URLs, implementation details) is stripped.

    Output files:
      - release-notes-en.md  (English, user-facing)
      - release-notes-de.md  (German, du-Form, user-facing)
      - release-notes-raw.md (raw git-cliff output, for GitHub Release details)

.PARAMETER RawChangelog
    Path to the raw changelog file generated by git-cliff.

.PARAMETER Version
    The version string (e.g., "1.2.0").

.PARAMETER OpenAIKey
    OpenAI API key (from GitHub Actions secret).

.PARAMETER Model
    OpenAI model to use. Default: gpt-4o-mini (fast, cheap, good enough for summaries).

.PARAMETER OutputDir
    Directory for output files. Default: current directory.
#>
param(
    [Parameter(Mandatory)][string]$RawChangelog,
    [Parameter(Mandatory)][string]$Version,
    [Parameter(Mandatory)][string]$OpenAIKey,
    [string]$Model = "gpt-4o-mini",
    [string]$OutputDir = "."
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $RawChangelog)) {
    Write-Error "Raw changelog not found: $RawChangelog"
    exit 1
}

$raw = Get-Content $RawChangelog -Raw -Encoding UTF8
if ([string]::IsNullOrWhiteSpace($raw)) {
    Write-Host "No changelog content — using fallback."
    $raw = "Minor improvements and bug fixes."
}

# Truncate to avoid excessive token usage (max ~3000 chars of commit log)
if ($raw.Length -gt 3000) {
    $raw = $raw.Substring(0, 3000) + "`n... (truncated)"
}

$systemPrompt = @"
You are a release notes writer for WhisPaste, a premium Windows desktop dictation app.
Your audience: non-technical Windows users (founders, freelancers, writers, consultants).

RULES:
- Write in a warm, professional, concise tone
- Group changes into clear sections: Highlights, Improvements, Bug Fixes (skip empty sections)
- Use simple language — no jargon, no code references, no file paths
- NEVER mention: API keys, webhook URLs, internal architecture, function names, file names,
  implementation details, server names (whisper-server, llama-server), database internals,
  crash reporter internals, CI/CD pipeline details
- Focus on USER IMPACT: what changed FOR THE USER, not what changed in the code
- Keep it compact: 5-15 bullet points max across all sections
- Each bullet: one sentence, starts with a verb or benefit
- If a change is purely internal (refactoring, CI, tests), skip it entirely

OUTPUT FORMAT (exactly):
===EN===
[English release notes in markdown, sections with ###]
===DE===
[German release notes in markdown, sections with ###, du-Form (informal "you")]
===END===
"@

$userPrompt = @"
Generate release notes for WhisPaste version $Version.

Here are the technical changes (from git commits):

$raw
"@

$body = @{
    model    = $Model
    messages = @(
        @{ role = "system"; content = $systemPrompt }
        @{ role = "user"; content = $userPrompt }
    )
    temperature  = 0.4
    max_tokens   = 1500
} | ConvertTo-Json -Depth 5

Write-Host "Calling OpenAI API ($Model) for release notes..."

try {
    $response = Invoke-RestMethod `
        -Uri "https://api.openai.com/v1/chat/completions" `
        -Method POST `
        -Headers @{
            "Authorization" = "Bearer $OpenAIKey"
            "Content-Type"  = "application/json"
        } `
        -Body $body `
        -TimeoutSec 60

    $content = $response.choices[0].message.content
    Write-Host "AI response received ($($content.Length) chars)"
} catch {
    Write-Warning "OpenAI API call failed: $_"
    Write-Host "Using raw changelog as fallback."

    # Fallback: use raw changelog without AI processing
    $enNotes = "## What's New in v$Version`n`n$raw"
    $deNotes = "## Neuigkeiten in v$Version`n`n$raw"
    $enNotes | Out-File -FilePath "$OutputDir/release-notes-en.md" -Encoding UTF8
    $deNotes | Out-File -FilePath "$OutputDir/release-notes-de.md" -Encoding UTF8
    $raw | Out-File -FilePath "$OutputDir/release-notes-raw.md" -Encoding UTF8
    exit 0
}

# Parse AI response
$enNotes = ""
$deNotes = ""

if ($content -match '===EN===([\s\S]*?)===DE===') {
    $enNotes = $Matches[1].Trim()
}
if ($content -match '===DE===([\s\S]*?)===END===') {
    $deNotes = $Matches[1].Trim()
}

# Fallback if parsing failed
if ([string]::IsNullOrWhiteSpace($enNotes)) {
    Write-Warning "Could not parse EN section from AI response. Using raw."
    $enNotes = "## What's New in v$Version`n`n$raw"
}
if ([string]::IsNullOrWhiteSpace($deNotes)) {
    Write-Warning "Could not parse DE section from AI response. Using EN as fallback."
    $deNotes = $enNotes
}

# Security post-filter: strip anything that looks like a secret or internal path
$secretPatterns = @(
    'sk-[a-zA-Z0-9]{10,}',
    'gsk_[a-zA-Z0-9]+',
    'Bearer\s+[a-zA-Z0-9._\-]+',
    'https?://[^\s]*supabase[^\s]*',
    'https?://[^\s]*discord[^\s]*webhook[^\s]*',
    'C:\\[^\s]+\.(go|ps1|yml|json|db|exe)',
    'whisper-server',
    'llama-server',
    'crashreporter',
    'captureSubprocessCrash',
    'logWarn|logError|logDebug',
    'buildEmbed',
    'sync\.RWMutex',
    '127\.0\.0\.1:\d+'
)

foreach ($pattern in $secretPatterns) {
    $enNotes = [regex]::Replace($enNotes, $pattern, '[REDACTED]', 'IgnoreCase')
    $deNotes = [regex]::Replace($deNotes, $pattern, '[REDACTED]', 'IgnoreCase')
}

# Check for accidental leaks
if ($enNotes -match '\[REDACTED\]' -or $deNotes -match '\[REDACTED\]') {
    Write-Warning "Security filter caught potential sensitive content — redacted."
}

# Write output files
$enNotes | Out-File -FilePath "$OutputDir/release-notes-en.md" -Encoding UTF8 -NoNewline
$deNotes | Out-File -FilePath "$OutputDir/release-notes-de.md" -Encoding UTF8 -NoNewline
$raw | Out-File -FilePath "$OutputDir/release-notes-raw.md" -Encoding UTF8 -NoNewline

Write-Host "Release notes generated:"
Write-Host "  EN: $OutputDir/release-notes-en.md ($($enNotes.Length) chars)"
Write-Host "  DE: $OutputDir/release-notes-de.md ($($deNotes.Length) chars)"
Write-Host "  Raw: $OutputDir/release-notes-raw.md ($($raw.Length) chars)"
