import Cocoa
import FlutterMacOS
import os.log

/// A clipboard content fingerprint -- mirrors Dart's `ClipboardFingerprint`
/// (`clipboard_fingerprint.dart`) exactly: byte length + FNV-1a 64 hash of
/// the UTF-8 bytes. Comparing content instead of predicting a `changeCount`
/// sequence number is required here (see that file's doc comment) because a
/// single Dart write can produce more than one `changeCount` bump and this
/// channel is separate from the platform clipboard channel, so dispatch
/// order between them is not guaranteed.
struct ClipboardFingerprint: Hashable {
  let length: Int
  let hash: Int64
}

/// FNV-1a, 64-bit -- bit-for-bit identical to Dart's `_fnv1a64`
/// (`clipboard_fingerprint.dart`). `&*`/`^=` wrap on overflow the same way
/// Dart's `& mask` does, so the two sides produce the same bit pattern;
/// [Int64] on the wire is just that pattern reinterpreted as signed, which
/// both `StandardMethodCodec` and this reinterpretation preserve losslessly.
func fnv1a64(_ bytes: [UInt8]) -> UInt64 {
  var hash: UInt64 = 0xcbf2_9ce4_8422_2325
  let prime: UInt64 = 0x0000_0100_0000_01b3
  for byte in bytes {
    hash ^= UInt64(byte)
    hash = hash &* prime
  }
  return hash
}

func fingerprintOfText(_ text: String) -> ClipboardFingerprint {
  let bytes = Array(text.utf8)
  return ClipboardFingerprint(length: bytes.count, hash: Int64(bitPattern: fnv1a64(bytes)))
}

/// Native mirror of Dart's `SelfWriteSuppressionRegistry` -- same 2s expiry,
/// same consume-on-check semantics (a failed/aborted write that never
/// changes the clipboard leaves the mark to expire on its own instead of
/// eating the user's next genuine copy indefinitely).
final class SelfWriteSuppressionRegistry {
  private var pending: [ClipboardFingerprint: Date] = [:]
  private let expiry: TimeInterval = 2.0

  func markSelfWrite(_ fingerprint: ClipboardFingerprint) {
    pending[fingerprint] = Date().addingTimeInterval(expiry)
  }

  func shouldSuppress(_ fingerprint: ClipboardFingerprint) -> Bool {
    guard let expiresAt = pending.removeValue(forKey: fingerprint) else { return false }
    return Date() < expiresAt
  }
}

/// Native macOS clipboard-history monitor (issue 04). Polls
/// `NSPasteboard.general.changeCount` and reports each new text/image entry
/// to Dart's `ClipboardHistoryMonitorService` over `com.whispaste.clipboard_history`
/// -- the same channel `MethodChannelSelfWriteSignal` invokes `markSelfWrite`
/// on (Dart -> native), so this host only *receives* that method, never
/// invokes it.
///
/// Privacy exclusion (`org.nspasteboard.{Transient,Concealed,AutoGenerated}Type`)
/// is reported as flags on every entry rather than filtered here -- the
/// actual drop decision is Dart-core (`shouldExcludeForPrivacy`, issue 01),
/// per PRD.md.
class ClipboardMonitorHost {
  private static let pollInterval: TimeInterval = 0.3
  private static let logger = OSLog(subsystem: "com.whispaste", category: "ClipboardMonitorHost")

  private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
  private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
  private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

  private let channel: FlutterMethodChannel
  private let registry = SelfWriteSuppressionRegistry()
  private var timer: Timer?
  private var lastChangeCount: Int

  init(messenger: FlutterBinaryMessenger) {
    channel = FlutterMethodChannel(name: "com.whispaste.clipboard_history", binaryMessenger: messenger)
    lastChangeCount = NSPasteboard.general.changeCount
    channel.setMethodCallHandler(handle)
    startPolling()
  }

  private func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    switch call.method {
    case "markSelfWrite":
      guard let args = call.arguments as? [String: Any],
            let length = args["length"] as? Int,
            let hash = args["hash"] as? Int
      else {
        result(nil)
        return
      }
      registry.markSelfWrite(ClipboardFingerprint(length: length, hash: Int64(hash)))
      result(nil)

    default:
      result(FlutterMethodNotImplemented)
    }
  }

  private func startPolling() {
    let t = Timer.scheduledTimer(withTimeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
      self?.pollPasteboard()
    }
    RunLoop.main.add(t, forMode: .common)
    timer = t
  }

  private func pollPasteboard() {
    let pb = NSPasteboard.general
    guard pb.changeCount != lastChangeCount else { return }
    lastChangeCount = pb.changeCount

    let types = pb.types ?? []
    let flags: (transient: Bool, concealed: Bool, autoGenerated: Bool) = (
      types.contains(Self.transientType),
      types.contains(Self.concealedType),
      types.contains(Self.autoGeneratedType)
    )

    if let text = pb.string(forType: .string), !text.isEmpty {
      let fingerprint = fingerprintOfText(text)
      if registry.shouldSuppress(fingerprint) {
        os_log("pollPasteboard: skipped self-write (%d bytes)", log: Self.logger, type: .debug, fingerprint.length)
        return
      }
      emitEntry(kind: "text", text: text, imageData: nil, flags: flags)
      return
    }

    if let imageData = pngData(from: pb) {
      // WhisPaste never writes images to the clipboard itself, so there is
      // no self-write fingerprint scheme for images to check against here.
      emitEntry(kind: "image", text: nil, imageData: imageData, flags: flags)
    }
  }

  private func pngData(from pasteboard: NSPasteboard) -> Data? {
    guard let image = NSImage(pasteboard: pasteboard),
          let tiff = image.tiffRepresentation,
          let rep = NSBitmapImageRep(data: tiff)
    else {
      return nil
    }
    return rep.representation(using: .png, properties: [:])
  }

  private func emitEntry(
    kind: String,
    text: String?,
    imageData: Data?,
    flags: (transient: Bool, concealed: Bool, autoGenerated: Bool)
  ) {
    var args: [String: Any] = [
      "kind": kind,
      "capturedAtMs": Int(Date().timeIntervalSince1970 * 1000),
      "transient": flags.transient,
      "concealed": flags.concealed,
      "autoGenerated": flags.autoGenerated,
    ]
    if let text {
      args["text"] = text
    }
    if let imageData {
      args["imageBytes"] = FlutterStandardTypedData(bytes: imageData)
    }
    channel.invokeMethod("clipEntryDetected", arguments: args)
  }

  func teardown() {
    timer?.invalidate()
    timer = nil
    channel.setMethodCallHandler(nil)
  }
}
