// Runner-owned MethodChannel bridge for the clipboard-history monitor
// (Ticket 05 Windows port -- .scratch/clipboard-quick-paste/issues/
// 05-windows-native.md). Behavioral precedent: macos/Runner/
// ClipboardMonitorHost.swift -- same channel name, same method contract, so
// the Dart side (self_write_signal.dart / clipboard_history_monitor_
// service.dart) needs zero platform branching.
//
// Channel contract (shared with macOS), channel "com.whispaste.
// clipboard_history":
//   Dart -> native: markSelfWrite({length, hash}) -- registers a 2s-expiry
//                    content fingerprint so the next observed identical
//                    clipboard write is skipped instead of reported as a
//                    new history entry (WhisPaste writing its own output
//                    back to the clipboard must not appear in its own
//                    history).
//   native -> Dart: clipEntryDetected({kind, capturedAtMs, transient,
//                    concealed, autoGenerated, text?, imageBytes?}).
//
// Unlike the Swift host (0.3s NSPasteboard.changeCount poll -- macOS has no
// native clipboard-change notification API), this is event-driven:
// AddClipboardFormatListener(owner) + WM_CLIPBOARDUPDATE, routed in from
// FlutterWindow::MessageHandler (mirrors the existing WM_DISPLAYCHANGE ->
// SidePanelHost::RebuildSensors wiring). This is also what ticket 05
// specifies, not a polling fallback.
//
// Privacy exclusion: macOS reports three org.nspasteboard.* flags
// (transient/concealed/autoGenerated); Windows has no three-way equivalent.
// Both of Windows' actual exclusion signals -- CanIncludeInClipboardHistory
// (DWORD payload, 0 = exclude, presence alone is not enough) and
// ExcludeClipboardContentFromMonitorProcessing (presence-only; used by
// KeePass/KeePassXC/1Password/NordPass/Sticky Password and private-browsing
// modes) -- collapse onto the single `concealed` flag on the outgoing
// clipEntryDetected call. Dart's shouldExcludeForPrivacy just ORs all three
// flags, so this loses no exclusion behavior; `transient`/`autoGenerated`
// are always sent false from this host.

#ifndef CLIPBOARD_MONITOR_HOST_H_
#define CLIPBOARD_MONITOR_HOST_H_

#include <flutter/encodable_value.h>
#include <flutter/flutter_engine.h>
#include <flutter/method_channel.h>
#include <flutter/standard_method_codec.h>
#include <windows.h>

#include <cstdint>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

class ClipboardMonitorHost {
 public:
  // |engine| must outlive this object. |owner| is the main Flutter HWND --
  // AddClipboardFormatListener needs a real HWND to route WM_CLIPBOARDUPDATE
  // to, and clipboard reads below use it as the OpenClipboard owner.
  ClipboardMonitorHost(flutter::FlutterEngine* engine, HWND owner);
  ~ClipboardMonitorHost();

  ClipboardMonitorHost(const ClipboardMonitorHost&) = delete;
  ClipboardMonitorHost& operator=(const ClipboardMonitorHost&) = delete;

  // Tear down native resources (clipboard listener + channel). Safe to call
  // multiple times. Must be called before main engine teardown.
  void Destroy();

  // Call from FlutterWindow::MessageHandler on WM_CLIPBOARDUPDATE.
  void HandleClipboardUpdate();

 private:
  void HandleMethodCall(
      const flutter::MethodCall<flutter::EncodableValue>& call,
      std::unique_ptr<flutter::MethodResult<flutter::EncodableValue>> result);

  void HandleMarkSelfWrite(const flutter::EncodableMap& args);

  // The actual body of HandleClipboardUpdate -- split out so the public
  // entry point stays a trivial destroyed_ guard.
  void ProcessClipboardChange();

  // Reads CF_UNICODETEXT. Empty if absent/empty (mirrors macOS's
  // `pb.string(forType: .string)` + `!text.isEmpty` guard).
  std::wstring ReadClipboardText() const;

  // Reads CF_BITMAP and PNG-encodes it via GDI+ (already linked/ref-counted
  // via GdiPlusHelper for the floating button/overlay windows). Empty if
  // absent or encoding fails.
  std::vector<uint8_t> ReadClipboardImagePng() const;

  // See the file doc comment's "Privacy exclusion" section.
  bool IsPrivacyExcluded() const;

  void EmitTextEntry(const std::string& utf8_text, bool concealed);
  void EmitImageEntry(const std::vector<uint8_t>& png, bool concealed);

  // ── Self-write suppression ─────────────────────────────────────────────
  // Mirrors Dart's SelfWriteSuppressionRegistry / Swift's
  // SelfWriteSuppressionRegistry bit-for-bit: same FNV-1a 64 content
  // fingerprint, same 2s expiry, same consume-on-check semantics (a hit
  // removes the pending entry; a miss/expiry leaves nothing behind to
  // wrongly suppress a later, genuinely new copy of the same text).
  struct Fingerprint {
    size_t length;
    uint64_t hash;
    bool operator==(const Fingerprint& other) const {
      return length == other.length && hash == other.hash;
    }
  };
  struct FingerprintHash {
    size_t operator()(const Fingerprint& f) const {
      return std::hash<size_t>()(f.length) ^
             (std::hash<uint64_t>()(f.hash) << 1);
    }
  };
  void MarkSelfWrite(const Fingerprint& fp);
  bool ShouldSuppress(const Fingerprint& fp);
  static Fingerprint FingerprintOfUtf8(const std::string& utf8);

  static constexpr double kSuppressionExpirySeconds = 2.0;
  // Value = absolute expiry tick (GetTickCount64()).
  std::unordered_map<Fingerprint, ULONGLONG, FingerprintHash>
      pending_self_writes_;

  flutter::FlutterEngine* engine_;  // Not owned
  HWND owner_;
  bool destroyed_ = false;
  bool listener_registered_ = false;

  std::unique_ptr<flutter::MethodChannel<flutter::EncodableValue>> channel_;
};

#endif  // CLIPBOARD_MONITOR_HOST_H_
