/// Reference audio clips and transcript resolver for the GPU probe tool.
///
/// The WAV files in `assets/` are PLACEHOLDER files generated by
/// `tools/gen_reference_wavs.dart`. A human must replace them with real
/// curated German audio + true transcripts before any meaningful live probe run.
library;

import 'dart:io';

import 'package:path/path.dart' as p;

import 'probe_types.dart';

/// The length variant of a reference clip.
enum ClipLength {
  /// Short clip (~5 seconds). Good for measuring startup overhead.
  short,

  /// Long clip (~60 seconds). Good for measuring throughput.
  long,
}

/// A resolved reference clip — WAV file + soll-transcript + metadata.
class ReferenceClip {
  const ReferenceClip({
    required this.length,
    required this.wavPath,
    required this.transcriptPath,
    this.language = 'de',
  });

  /// Which clip variant this is.
  final ClipLength length;

  /// Absolute path to the WAV file.
  final String wavPath;

  /// Absolute path to the soll-transcript `.txt` file.
  final String transcriptPath;

  /// BCP-47 language code. Always `'de'` for reference clips.
  final String language;
}

/// Resolves reference clips relative to the package assets directory.
///
/// Resolution order:
/// 1. `WHISPASTE_GPU_PROBE_ASSETS` environment variable (useful in CI / tests
///    run from an arbitrary working directory).
/// 2. `<package-root>/assets/` where the package root is inferred from
///    [Platform.script] — works when running from the package directory with
///    `dart test` or `dart run`.
/// 3. The current working directory (`Directory.current`) as a last resort.
class ReferenceClipProvider {
  ReferenceClipProvider() : _assetsDir = _resolveAssetsDir();

  final String _assetsDir;

  /// The resolved assets directory path.
  String get assetsDir => _assetsDir;

  /// Returns the [ReferenceClip] for the given [length].
  ReferenceClip clip(ClipLength length) {
    return switch (length) {
      ClipLength.short => ReferenceClip(
        length: ClipLength.short,
        wavPath: p.join(_assetsDir, 'reference_short.wav'),
        transcriptPath: p.join(_assetsDir, 'reference_short.txt'),
      ),
      ClipLength.long => ReferenceClip(
        length: ClipLength.long,
        wavPath: p.join(_assetsDir, 'reference_long.wav'),
        transcriptPath: p.join(_assetsDir, 'reference_long.txt'),
      ),
    };
  }

  static String _resolveAssetsDir() {
    // 1. Explicit override via environment variable.
    final envOverride = Platform.environment['WHISPASTE_GPU_PROBE_ASSETS'];
    if (envOverride != null && envOverride.isNotEmpty) {
      return envOverride;
    }

    // 2. Relative to the package root inferred from Platform.script.
    //    `dart test` sets Platform.script to the test file path, which is
    //    inside `test/`, so we walk up to `packages/whispaste_gpu_probe/`.
    //    `dart run tools/gen_reference_wavs.dart` sets it to the script path
    //    inside `tools/`, same walk-up logic applies.
    final scriptUri = Platform.script;
    if (scriptUri.scheme == 'file') {
      final scriptPath = scriptUri.toFilePath();
      // Walk up until we find a directory that contains `pubspec.yaml`.
      var dir = Directory(p.dirname(scriptPath));
      for (var i = 0; i < 6; i++) {
        final candidate = File(p.join(dir.path, 'pubspec.yaml'));
        if (candidate.existsSync()) {
          return p.join(dir.path, 'assets');
        }
        final parent = dir.parent;
        if (parent.path == dir.path) break;
        dir = parent;
      }
    }

    // 3. Fallback: current working directory / assets.
    return p.join(Directory.current.path, 'assets');
  }
}

/// Returns a [ProbeContext] wired up to the given reference [length] clip.
///
/// [modelPath] and [workDir] must be provided by the caller — they are
/// machine-specific and not bundled with the package.
ProbeContext referenceProbeContext(
  ClipLength length, {
  required String modelPath,
  required String workDir,
  Duration timeout = const Duration(minutes: 2),
}) {
  final clip = ReferenceClipProvider().clip(length);
  return ProbeContext(
    referenceWavPath: clip.wavPath,
    modelPath: modelPath,
    workDir: workDir,
    language: clip.language,
    timeout: timeout,
  );
}
